// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/7StaSH7/practicum-diploma/internal/service/auth (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/auth_service_mock.go -package=mocks github.com/7StaSH7/practicum-diploma/internal/service/auth Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	auth "github.com/7StaSH7/practicum-diploma/internal/dto/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Refresh mocks base method.
func (m *MockService) Refresh(ctx context.Context, refreshToken string) (auth.AuthResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, refreshToken)
	ret0, _ := ret[0].(auth.AuthResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockServiceMockRecorder) Refresh(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockService)(nil).Refresh), ctx, refreshToken)
}

// Signin mocks base method.
func (m *MockService) Signin(ctx context.Context, login, password string) (auth.AuthResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signin", ctx, login, password)
	ret0, _ := ret[0].(auth.AuthResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signin indicates an expected call of Signin.
func (mr *MockServiceMockRecorder) Signin(ctx, login, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signin", reflect.TypeOf((*MockService)(nil).Signin), ctx, login, password)
}

// Signup mocks base method.
func (m *MockService) Signup(ctx context.Context, login, password string) (auth.AuthResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signup", ctx, login, password)
	ret0, _ := ret[0].(auth.AuthResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signup indicates an expected call of Signup.
func (mr *MockServiceMockRecorder) Signup(ctx, login, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signup", reflect.TypeOf((*MockService)(nil).Signup), ctx, login, password)
}
